"""Expand patients.json with Tamil person-names from ai4bharat/naamapadam.

Usage:
    python scripts/build_patients.py --count 10000

Keeps the existing hand-crafted seed patients (they carry the spelling
collisions used in the acceptance tests) and appends N additional rows
mined from the Tamil split of naamapadam, with synthetic ward/bed/age
metadata. The English form (`name_en`) is auto-generated by our
romanizer so voice queries in Tamil-English work out of the box.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from collections import Counter
from datetime import date, timedelta
from typing import Iterable

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PATIENTS_PATH = os.path.join(ROOT, "backend", "patients.json")

sys.path.insert(0, ROOT)
from backend.romanize import romanize  # noqa: E402


def _extract_per_spans(dataset) -> Iterable[str]:
    label_names = dataset.features["ner_tags"].feature.names
    try:
        b_per = label_names.index("B-PER")
    except ValueError:
        b_per = next(i for i, n in enumerate(label_names) if n.endswith("-PER") and n.startswith("B"))
    try:
        i_per = label_names.index("I-PER")
    except ValueError:
        i_per = next(i for i, n in enumerate(label_names) if n.endswith("-PER") and n.startswith("I"))

    for row in dataset:
        words = row.get("words") or row.get("tokens") or []
        tags = row["ner_tags"]
        current: list[str] = []
        for word, tag in zip(words, tags):
            if tag == b_per:
                if current:
                    yield " ".join(current)
                current = [word]
            elif tag == i_per and current:
                current.append(word)
            else:
                if current:
                    yield " ".join(current)
                    current = []
        if current:
            yield " ".join(current)


def _looks_like_name(text: str) -> bool:
    t = text.strip()
    if not t or len(t) < 2:
        return False
    if any(ch.isdigit() for ch in t):
        return False
    tokens = t.split()
    if len(tokens) > 5:
        return False
    return True


def _load_tamil_names(count: int) -> list[str]:
    from datasets import load_dataset

    print("Loading ai4bharat/naamapadam [ta] (this may download ~1GB on first run)…")
    splits = []
    for split in ("train", "validation", "test"):
        try:
            splits.append(load_dataset("ai4bharat/naamapadam", "ta", split=split))
        except Exception as exc:
            print(f"  skipping split={split}: {exc}")

    freq: Counter[str] = Counter()
    for ds in splits:
        for name in _extract_per_spans(ds):
            if _looks_like_name(name):
                freq[name.strip()] += 1

    ranked = [n for n, _ in freq.most_common()]
    print(f"  found {len(ranked):,} unique Tamil person-names")

    rng = random.Random(42)
    head = ranked[: min(count, len(ranked))]
    if len(head) < count and ranked:
        extras = rng.sample(ranked, min(count - len(head), len(ranked)))
        head = list(dict.fromkeys(head + extras))
    return head[:count]


def _synth_metadata(i: int, name_key: str, rng: random.Random) -> dict:
    ward = f"W{(i % 12) + 1}"
    bed = f"B{(i % 60) + 1:02d}"
    mrn = f"{ward}-{bed}-{i + 1000:05d}"
    age = 18 + (abs(hash(name_key)) % 72)
    gender = "F" if abs(hash(name_key)) % 2 == 0 else "M"
    admission = date(2026, 1, 1) + timedelta(days=abs(hash(name_key)) % 120)
    return {
        "mrn": mrn,
        "age": age,
        "gender": gender,
        "ward": ward,
        "bed": bed,
        "admission_date": admission.isoformat(),
        "photo_url": "",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=10_000,
                        help="Additional patients to append (default 10000).")
    parser.add_argument("--out", default=PATIENTS_PATH)
    parser.add_argument("--keep-seed", action="store_true", default=True,
                        help="Keep the hand-crafted seed patients (default).")
    parser.add_argument("--replace", dest="keep_seed", action="store_false",
                        help="Replace the seed rather than appending.")
    args = parser.parse_args()

    seed: list[dict] = []
    if args.keep_seed and os.path.exists(args.out):
        with open(args.out, encoding="utf-8") as f:
            seed = json.load(f)
        print(f"Keeping {len(seed)} existing seed patients")

    seen_names = {(p.get("name_ta") or p.get("name_en") or "").strip() for p in seed}

    names = _load_tamil_names(args.count + len(seed))
    rng = random.Random(42)
    added: list[dict] = []
    for name_ta in names:
        if name_ta in seen_names:
            continue
        patient = {
            "name_en": romanize(name_ta),
            "name_ta": name_ta,
            **_synth_metadata(len(seed) + len(added), name_ta, rng),
        }
        added.append(patient)
        seen_names.add(name_ta)
        if len(added) >= args.count:
            break

    combined = seed + added
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(combined, f, ensure_ascii=False, indent=2)
    print(f"Wrote {len(combined):,} patients to {args.out}  (+{len(added):,} new)")


if __name__ == "__main__":
    main()
